//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmunicipio
    {
        public cmunicipio()
        {
            this.customer = new HashSet<customer>();
        }
    
        public int idcMunicipio { get; set; }
        public int iddEstado { get; set; }
        public string Clave { get; set; }
        public string Municipio { get; set; }
        public string CabeceraMunicipal { get; set; }
    
        public virtual destado destado { get; set; }
        public virtual ICollection<customer> customer { get; set; }
    }
}
