//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cstate
    {
        public cstate()
        {
            this.product = new HashSet<product>();
            this.tax = new HashSet<tax>();
            this.user = new HashSet<user>();
            this.customer = new HashSet<customer>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<product> product { get; set; }
        public virtual ICollection<tax> tax { get; set; }
        public virtual ICollection<user> user { get; set; }
        public virtual ICollection<customer> customer { get; set; }
    }
}
