//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int id { get; set; }
        public string name { get; set; }
        public string comercial_name { get; set; }
        public string RFC { get; set; }
        public string CP { get; set; }
        public string Street { get; set; }
        public int idEstado { get; set; }
        public int idMunicipio { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> idState { get; set; }
        public string NoExt { get; set; }
        public string NoInt { get; set; }
        public string email { get; set; }
        public string CodeTaxRegime { get; set; }
    
        public virtual cmunicipio cmunicipio { get; set; }
        public virtual cstate cstate { get; set; }
        public virtual destado destado { get; set; }
        public virtual user user { get; set; }
    }
}
