//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class destado
    {
        public destado()
        {
            this.cmunicipio = new HashSet<cmunicipio>();
            this.customer = new HashSet<customer>();
        }
    
        public int iddEstado { get; set; }
        public string Nombre { get; set; }
        public string Pais { get; set; }
        public string Valor { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<cmunicipio> cmunicipio { get; set; }
        public virtual ICollection<customer> customer { get; set; }
    }
}
