//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.product_tax = new HashSet<product_tax>();
        }
    
        public int id { get; set; }
        public string claveProdServ { get; set; }
        public string claveUnidad { get; set; }
        public string NoIdentificacion { get; set; }
        public string Unidad { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public Nullable<int> idUser { get; set; }
        public System.DateTime date_create { get; set; }
        public int idState { get; set; }
    
        public virtual cstate cstate { get; set; }
        public virtual ICollection<product_tax> product_tax { get; set; }
        public virtual user user { get; set; }
    }
}
