//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax
    {
        public tax()
        {
            this.product_tax = new HashSet<product_tax>();
        }
    
        public int id { get; set; }
        public System.DateTime date_create { get; set; }
        public int idState { get; set; }
        public string name { get; set; }
        public string type_ambit { get; set; }
        public string type { get; set; }
        public decimal tasa { get; set; }
        public string claveImpuesto { get; set; }
        public string tipo_factor { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual cstate cstate { get; set; }
        public virtual ICollection<product_tax> product_tax { get; set; }
        public virtual user user { get; set; }
    }
}
