//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.invoice = new HashSet<invoice>();
            this.product = new HashSet<product>();
            this.tax = new HashSet<tax>();
            this.customer = new HashSet<customer>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> idState { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public string name { get; set; }
        public string fiscal_name { get; set; }
        public string rfc { get; set; }
        public string CodeTaxRegime { get; set; }
        public string PrivateCode { get; set; }
        public string UserPacFC { get; set; }
        public string PassPacFC { get; set; }
        public string cp { get; set; }
    
        public virtual cstate cstate { get; set; }
        public virtual ICollection<invoice> invoice { get; set; }
        public virtual ICollection<product> product { get; set; }
        public virtual ICollection<tax> tax { get; set; }
        public virtual ICollection<customer> customer { get; set; }
    }
}
