//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models.SAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class f4_c_claveunidad
    {
        public int id { get; set; }
        public string c_ClaveUnidad { get; set; }
        public string Nombre { get; set; }
        public string Descripción { get; set; }
        public string Nota { get; set; }
        public string Fechadeiniciodevigencia { get; set; }
        public string Fechadefindevigencia { get; set; }
        public string Símbolo { get; set; }
    }
}
