//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models.SAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class f4_c_pais
    {
        public int id { get; set; }
        public string c_Pais { get; set; }
        public string Descripción { get; set; }
        public string Formato_de_código_postal { get; set; }
        public string Formato_de_Registro_de_Identidad_Tributaria { get; set; }
        public string Validación_del_Registro_de_Identidad_Tributaria { get; set; }
        public string Agrupaciones { get; set; }
    }
}
