//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models.SAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class f4_c_codigopostal
    {
        public int id { get; set; }
        public string c_CodigoPostal { get; set; }
        public string c_Estado { get; set; }
        public string c_Municipio { get; set; }
        public string c_Localidad { get; set; }
    }
}
