//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models.SAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class f4_c_tasaocuota
    {
        public int id { get; set; }
        public string RangoOFijo { get; set; }
        public string Valor_mínimo { get; set; }
        public string Valor_máximo { get; set; }
        public string Impuesto { get; set; }
        public string Factor { get; set; }
        public string Traslado { get; set; }
        public string Retención { get; set; }
        public string Fecha_inicio_de_vigencia { get; set; }
        public string Fecha_fin_de_vigencia { get; set; }
    }
}
