//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models.SAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class f4_c_impuesto
    {
        public int id { get; set; }
        public string c_Impuesto { get; set; }
        public string Descripción { get; set; }
        public string Retención { get; set; }
        public string Traslado { get; set; }
        public string Local_o_federal { get; set; }
        public string Entidad_en_la_que_aplica { get; set; }
    }
}
