//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models.SAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class f4_c_claveprodserv
    {
        public int id { get; set; }
        public string c_ClaveProdServ { get; set; }
        public string Descripción { get; set; }
        public string Incluir_IVA_trasladado { get; set; }
        public string Incluir_IEPS_trasladado { get; set; }
        public string Complemento_que_debe_incluir { get; set; }
        public string FechaInicioVigencia { get; set; }
        public string FechaFinVigencia { get; set; }
        public string Palabras_similares { get; set; }
    }
}
