//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models.SAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class f4_c_regimenfiscal
    {
        public int id { get; set; }
        public string c_RegimenFiscal { get; set; }
        public string Descripción { get; set; }
        public string Física { get; set; }
        public string Moral { get; set; }
        public string Fecha_de_inicio_de_vigencia { get; set; }
        public string Fecha_de_fin_de_vigencia { get; set; }
    }
}
