//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdeleon_Facturacion.Models.SAT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class satEntities : DbContext
    {
        public satEntities()
            : base("name=satEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<f4_c_aduana> f4_c_aduana { get; set; }
        public DbSet<f4_c_caducidadfolios> f4_c_caducidadfolios { get; set; }
        public DbSet<f4_c_claveprodserv> f4_c_claveprodserv { get; set; }
        public DbSet<f4_c_claveunidad> f4_c_claveunidad { get; set; }
        public DbSet<f4_c_codigopostal> f4_c_codigopostal { get; set; }
        public DbSet<f4_c_formapago> f4_c_formapago { get; set; }
        public DbSet<f4_c_impuesto> f4_c_impuesto { get; set; }
        public DbSet<f4_c_metodopago> f4_c_metodopago { get; set; }
        public DbSet<f4_c_moneda> f4_c_moneda { get; set; }
        public DbSet<f4_c_numpedimentoaduana> f4_c_numpedimentoaduana { get; set; }
        public DbSet<f4_c_pais> f4_c_pais { get; set; }
        public DbSet<f4_c_patenteaduanal> f4_c_patenteaduanal { get; set; }
        public DbSet<f4_c_regimenfiscal> f4_c_regimenfiscal { get; set; }
        public DbSet<f4_c_tasaocuota> f4_c_tasaocuota { get; set; }
        public DbSet<f4_c_tipodecomprobante> f4_c_tipodecomprobante { get; set; }
        public DbSet<f4_c_tipofactor> f4_c_tipofactor { get; set; }
        public DbSet<f4_c_tiporelacion> f4_c_tiporelacion { get; set; }
        public DbSet<f4_c_usocfdi> f4_c_usocfdi { get; set; }
        public DbSet<cexportacion> cexportacion { get; set; }
        public DbSet<cobjetoimpuesto> cobjetoimpuesto { get; set; }
        public DbSet<c_meses> c_meses { get; set; }
        public DbSet<c_periodicidad> c_periodicidad { get; set; }
    }
}
